[package]
name = "composable-indexes-props"
version = "0.1.0"
edition = "2024"

[dependencies]
composable-indexes-core = { path = "../composable-indexes-core" }
proptest = { version = "1.6.0" }

[dev-dependencies]
proptest = { version = "*", features = ["attr-macro"] }
proptest-derive = "0.5.1"
